services:
  db:
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=TASK_MANAGER
    image: postgres:14
    volumes:
      - dbdata:/var/lib/postgresql/data
